# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

jobs:
- job:
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Java8:
        JDK_VERSION: 1.8
      Java11:
        JDK_VERSION: 1.11
  steps:
  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew' 
      options: -x check --scan --no-daemon
      tasks: 'build' 
      jdkVersionOption: $(JDK_VERSION)
    displayName: Build

  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew' 
      options:  --scan --no-daemon
      tasks: 'testcontainers:check javadoc' 
      publishJUnitResults: true 
      testResultsFiles: '**/TEST-*.xml' # Required when publishJUnitResults == True
      testRunTitle: Core Tests Java $(JDK_VERSION)
      jdkVersionOption: $(JDK_VERSION)
    displayName: Core Tests
